import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/website/Header";
import Footer from "@/components/website/Footer";
import StoreProvider from "@/redux/StoreProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { getProfile } from "@/utils/serverapi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({ children }) {
  const getMe = await getProfile();

  const user = getMe?.success
    ? getMe.user
    : null;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-[#F9F8F6] text-[#2C2A29] min-h-screen flex flex-col">
        <StoreProvider>
         <Header user={user} />
          <main className="flex-grow max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 pt-6 pb-16">
            {children}
          </main>
          <Footer />
          <ToastContainer position="bottom-center" autoClose={2000} style={{ bottom: "80px", }} />
        </StoreProvider>

      </body>
    </html>
  );
}
